import { useRef, useState } from "react";
import { useNavigate } from "react-router-dom";
import { Loader2, Download } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { useStore } from "@/context/StoreContext";
import { isAuthenticated, getCurrentUser } from "@/lib/auth";
import { createFreeOrder } from "@/lib/checkout-api";
import FREE_DOWNLOADS from "@/data/free-downloads.json";

/**
 * FreeCheckoutButton — handles the cart's free-only checkout path.
 *
 * Resilience strategy (added 2026-05-21):
 *   The server-side /order-free endpoint can be missing on Hostinger when the
 *   zz-hk-free-orders.php mu-plugin hasn't been uploaded yet (404 rest_no_route).
 *   We now do a "server-first, client-fallback" dance:
 *
 *     1. Try createFreeOrder() against the server. If it returns success,
 *        we use the server-issued download URLs (signed, audit-trailed,
 *        email-delivered) — same as before, no behaviour change.
 *
 *     2. If the server fails specifically with a "no route" error
 *        (rest_no_route / 404 / "No route was found...") OR a network
 *        error, we fall back to a static map of public download URLs
 *        baked into the bundle at build time. Each free product in the
 *        catalog already has a public pub.hyperagent.com URL stored as
 *        its WC `downloads[].file`, so we can open them directly in new
 *        tabs without any server round-trip.
 *
 *     3. For any OTHER server error (validation / paid item in free cart
 *        / 422 etc), we surface the message — those are real business
 *        rule violations, not infrastructure problems.
 *
 *   The static map ships in /data/free-downloads.json (regenerated by the
 *   `scripts/refresh-free-downloads.ts` task whenever new free products
 *   are added). When the mu-plugin lands on prod, the server path wins
 *   automatically and the fallback never fires.
 */

interface DownloadMapEntry { name: string; file: string }
const downloadMap = FREE_DOWNLOADS as Record<string, DownloadMapEntry[]>;

function openDownloads(downloads: { name?: string; file?: string; download_url?: string }[]): number {
  // Sequential window.open to avoid popup blocker batching.
  // Browsers allow N=1 popup per click without prompt; for N>1 we use anchor clicks
  // which are gesture-attributed and bypass the popup blocker on most browsers.
  let opened = 0;
  for (const dl of downloads) {
    const url = dl.file || dl.download_url;
    if (!url) continue;
    const a = document.createElement("a");
    a.href = url;
    a.download = (dl.name || "download").replace(/[^a-z0-9._-]+/gi, "_");
    a.target = "_blank";
    a.rel = "noopener";
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    opened++;
  }
  return opened;
}

function looksLikeRouteMissing(msg: string): boolean {
  const m = msg.toLowerCase();
  return (
    m.includes("rest_no_route") ||
    m.includes("no route was found") ||
    m.includes("request failed (404)") ||
    m.includes("404") ||
    m.includes("network error")
  );
}

export default function FreeCheckoutButton({
  className = "",
  onAfterCheckout,
  onSubmitting,
}: {
  className?: string;
  onAfterCheckout?: () => void;
  onSubmitting?: (active: boolean) => void;
}) {
  const { state, dispatch } = useStore();
  const navigate = useNavigate();
  const [busy, setBusy] = useState(false);
  const submittingRef = useRef(false);

  const setSubmitting = (active: boolean) => {
    submittingRef.current = active;
    setBusy(active);
    if (onSubmitting) onSubmitting(active);
  };

  const handleClick = async () => {
    if (submittingRef.current) return;

    if (!isAuthenticated()) {
      toast.info("Please sign in to claim your free downloads.");
      navigate("/login?next=/cart");
      return;
    }
    const user = getCurrentUser();
    if (!user?.email) {
      toast.error("We couldn't find your email. Please log in again.");
      navigate("/login?next=/cart");
      return;
    }
    if (state.cart.length === 0) {
      toast.error("Your cart is empty.");
      return;
    }

    // Snapshot cart at click time (qty hard-capped to 1 per product —
    // matches server-side invariant for free orders)
    const seenIds = new Set<number>();
    const itemsSnapshot: { product_id: number; quantity: number }[] = [];
    for (const ci of state.cart) {
      const pid = Number(ci.product.id);
      if (!pid || seenIds.has(pid)) continue;
      seenIds.add(pid);
      itemsSnapshot.push({ product_id: pid, quantity: 1 });
    }

    setSubmitting(true);
    try {
      // ─── Server path (canonical) ────────────────────────────────────
      const res = await createFreeOrder({
        items: itemsSnapshot,
        email: user.email,
        first_name: user.first_name || user.name?.split(" ")[0] || "",
        last_name:  user.last_name  || user.name?.split(" ").slice(1).join(" ") || "",
      });

      // Open downloads in new tabs immediately so the user gets the
      // file even if the email is delayed.
      const opened = openDownloads(res.downloads || []);
      dispatch({ type: "CLEAR_CART" });
      window.dispatchEvent(new Event("yavi:wallet:refresh"));
      toast.success(
        `Order #${res.order_number} confirmed — ${opened} download${opened === 1 ? "" : "s"} opened. We also emailed the links to ${res.email}.`
      );
      if (onAfterCheckout) onAfterCheckout();
      navigate("/account/downloads", { replace: true });
      return;
    } catch (e) {
      const msg = e instanceof Error ? e.message : "Could not complete free checkout";

      // ─── Client fallback for missing /order-free route ──────────────
      // If the mu-plugin isn't deployed yet (rest_no_route / 404) we
      // still want the user to get their free downloads. We open the
      // pre-baked public URLs from the static map.
      if (looksLikeRouteMissing(msg)) {
        const opened: { name?: string; file?: string }[] = [];
        const missing: number[] = [];
        for (const it of itemsSnapshot) {
          const dls = downloadMap[String(it.product_id)];
          if (dls && dls.length > 0) opened.push(...dls);
          else missing.push(it.product_id);
        }

        if (opened.length === 0) {
          toast.error(
            missing.length > 0
              ? `Couldn't find download files for ${missing.length} product(s). Please contact team@shop.hackknow.com.`
              : "Free download is temporarily unavailable. Please try again in a moment."
          );
          return;
        }

        const count = openDownloads(opened);
        dispatch({ type: "CLEAR_CART" });
        window.dispatchEvent(new Event("yavi:wallet:refresh"));
        if (missing.length > 0) {
          toast.warning(
            `Opened ${count} download${count === 1 ? "" : "s"}. ${missing.length} item(s) couldn't be resolved — we'll email those to ${user.email} shortly.`
          );
        } else {
          toast.success(
            `${count} free download${count === 1 ? "" : "s"} opened in new tab${count === 1 ? "" : "s"}. Check your downloads folder.`
          );
        }
        if (onAfterCheckout) onAfterCheckout();
        // Stay on cart so the user can verify the tabs opened. No
        // navigation to /account/downloads here because the server
        // order wasn't created in this branch.
        return;
      }

      // ─── Real business-rule errors ──────────────────────────────────
      if (msg.includes("duplicate") || msg.includes("already")) {
        toast.info("Your previous request is still being processed — please wait a moment.");
      } else {
        toast.error(msg);
      }
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <Button
      onClick={handleClick}
      disabled={busy || state.cart.length === 0}
      className={`w-full h-12 bg-green-600 text-white hover:bg-green-700 rounded-full font-bold gap-2 disabled:opacity-60 disabled:cursor-not-allowed ${className}`}
      data-testid="free-checkout-button"
    >
      {busy ? (
        <>
          <Loader2 className="w-4 h-4 animate-spin" />
          Generating your downloads…
        </>
      ) : (
        <>
          <Download className="w-4 h-4" />
          Click to Download (Free)
        </>
      )}
    </Button>
  );
}
