"""Semantic name pools per category. Each entry maps to a unique product name."""

# 13 categories, total 206 templates. Each category has at least N unique names.
NAME_POOLS = {
    'Accounting': [
        ('Small Business Bookkeeping Ledger', 'small-business-bookkeeping-ledger', 'small business bookkeeping ledger excel'),
        ('Cash Flow Statement Template', 'cash-flow-statement-template', 'cash flow statement template excel'),
        ('Profit and Loss Statement', 'profit-and-loss-statement', 'profit and loss statement excel'),
        ('Balance Sheet Template', 'balance-sheet-template', 'balance sheet template excel'),
        ('General Ledger Worksheet', 'general-ledger-worksheet', 'general ledger excel template'),
        ('Accounts Payable Tracker', 'accounts-payable-tracker', 'accounts payable tracker excel'),
        ('Accounts Receivable Tracker', 'accounts-receivable-tracker', 'accounts receivable tracker excel'),
        ('Trial Balance Worksheet', 'trial-balance-worksheet', 'trial balance worksheet excel'),
        ('Petty Cash Log Template', 'petty-cash-log-template', 'petty cash log excel template'),
    ],
    'Budget': [
        ('Monthly Personal Budget Planner', 'monthly-personal-budget-planner', 'monthly personal budget excel'),
        ('Family Household Budget Tracker', 'family-household-budget-tracker', 'family household budget excel'),
        ('Annual Yearly Budget Planner', 'annual-yearly-budget-planner', 'annual budget planner excel'),
        ('Weekly Cash Flow Budget Sheet', 'weekly-cash-flow-budget-sheet', 'weekly cash flow budget excel'),
        ('College Student Budget Worksheet', 'college-student-budget-worksheet', 'college student budget excel'),
        ('Wedding Budget Planner Spreadsheet', 'wedding-budget-planner-spreadsheet', 'wedding budget planner excel'),
        ('Vacation Trip Budget Planner', 'vacation-trip-budget-planner', 'vacation trip budget excel'),
        ('Construction Project Budget Sheet', 'construction-project-budget-sheet', 'construction project budget excel'),
        ('Event Budget Tracker Worksheet', 'event-budget-tracker-worksheet', 'event budget tracker excel'),
        ('Marketing Budget Plan Template', 'marketing-budget-plan-template', 'marketing budget plan excel'),
        ('Office Department Budget Sheet', 'office-department-budget-sheet', 'office department budget excel'),
        ('Startup Founder Budget Worksheet', 'startup-founder-budget-worksheet', 'startup budget worksheet excel'),
        ('Zero Based Budget Template', 'zero-based-budget-template', 'zero based budget template excel'),
        ('Christmas Holiday Budget Planner', 'christmas-holiday-budget-planner', 'christmas holiday budget excel'),
        ('Newborn Baby Budget Planner', 'newborn-baby-budget-planner', 'newborn baby budget excel'),
        ('Restaurant Operating Budget', 'restaurant-operating-budget', 'restaurant operating budget excel'),
        ('Retirement Income Budget Planner', 'retirement-income-budget-planner', 'retirement income budget excel'),
        ('Real Estate Investment Budget', 'real-estate-investment-budget', 'real estate investment budget excel'),
        ('Non Profit Organisation Budget', 'non-profit-organisation-budget', 'non profit organisation budget excel'),
        ('Church Ministry Budget Template', 'church-ministry-budget-template', 'church ministry budget excel'),
        ('Home Renovation Budget Planner', 'home-renovation-budget-planner', 'home renovation budget excel'),
        ('Salary Income Budget Worksheet', 'salary-income-budget-worksheet', 'salary income budget excel'),
        ('Bi Weekly Paycheck Budget', 'bi-weekly-paycheck-budget', 'bi weekly paycheck budget excel'),
        ('Quarterly Budget Review Sheet', 'quarterly-budget-review-sheet', 'quarterly budget review excel'),
        ('Daily Expenses Budget Tracker', 'daily-expenses-budget-tracker', 'daily expenses budget tracker excel'),
        ('Mortgage Loan Repayment Budget', 'mortgage-loan-repayment-budget', 'mortgage loan repayment budget excel'),
    ],
    'Calculator': [
        ('Loan EMI Calculator Excel', 'loan-emi-calculator-excel', 'loan emi calculator excel'),
        ('Mortgage Amortisation Calculator', 'mortgage-amortisation-calculator', 'mortgage amortisation calculator excel'),
    ],
    'Calendars': [
        ('Annual Wall Calendar Planner', 'annual-wall-calendar-planner', 'annual wall calendar planner excel'),
        ('Editorial Content Calendar', 'editorial-content-calendar', 'editorial content calendar excel'),
    ],
    'Chart': [
        ('Sales Performance Chart Template', 'sales-performance-chart-template', 'sales performance chart excel'),
        ('Gantt Project Chart Template', 'gantt-project-chart-template', 'gantt project chart excel'),
        ('Organisation Hierarchy Chart', 'organisation-hierarchy-chart', 'organisation hierarchy chart excel'),
        ('Pie Distribution Chart Template', 'pie-distribution-chart-template', 'pie distribution chart excel'),
        ('Bar Comparison Chart Template', 'bar-comparison-chart-template', 'bar comparison chart excel'),
        ('Line Trend Chart Template', 'line-trend-chart-template', 'line trend chart excel'),
        ('Area Stack Chart Template', 'area-stack-chart-template', 'area stack chart excel'),
        ('Scatter Correlation Chart', 'scatter-correlation-chart', 'scatter correlation chart excel'),
        ('Bubble Insight Chart Template', 'bubble-insight-chart-template', 'bubble insight chart excel'),
        ('Doughnut Breakdown Chart', 'doughnut-breakdown-chart', 'doughnut breakdown chart excel'),
        ('Histogram Frequency Chart', 'histogram-frequency-chart', 'histogram frequency chart excel'),
        ('Pareto Priority Chart Template', 'pareto-priority-chart-template', 'pareto priority chart excel'),
        ('Funnel Conversion Chart Template', 'funnel-conversion-chart-template', 'funnel conversion chart excel'),
        ('Waterfall Variance Chart', 'waterfall-variance-chart', 'waterfall variance chart excel'),
        ('Radar Skills Chart Template', 'radar-skills-chart-template', 'radar skills chart excel'),
        ('Sunburst Hierarchy Chart', 'sunburst-hierarchy-chart', 'sunburst hierarchy chart excel'),
        ('Tree Map Visualisation Chart', 'tree-map-visualisation-chart', 'tree map visualisation chart excel'),
        ('Combo Mixed Chart Template', 'combo-mixed-chart-template', 'combo mixed chart excel'),
        ('Stock OHLC Chart Template', 'stock-ohlc-chart-template', 'stock ohlc chart excel'),
        ('Box Plot Statistics Chart', 'box-plot-statistics-chart', 'box plot statistics chart excel'),
        ('Heatmap Density Chart Template', 'heatmap-density-chart-template', 'heatmap density chart excel'),
        ('Stacked Column Chart Template', 'stacked-column-chart-template', 'stacked column chart excel'),
        ('Surface Topographic Chart', 'surface-topographic-chart', 'surface topographic chart excel'),
        ('Polar Area Chart Template', 'polar-area-chart-template', 'polar area chart excel'),
        ('Waterfall Cash Flow Chart', 'waterfall-cash-flow-chart', 'waterfall cash flow chart excel'),
        ('Quadrant Analysis Chart', 'quadrant-analysis-chart', 'quadrant analysis chart excel'),
        ('KPI Dashboard Chart Template', 'kpi-dashboard-chart-template', 'kpi dashboard chart excel'),
    ],
    'Financial-Management': [
        ('Financial Statement Tracker', 'financial-statement-tracker', 'financial statement tracker excel'),
        ('Investment Portfolio Tracker', 'investment-portfolio-tracker', 'investment portfolio tracker excel'),
        ('Retirement Planning Worksheet', 'retirement-planning-worksheet', 'retirement planning worksheet excel'),
        ('Net Worth Statement Template', 'net-worth-statement-template', 'net worth statement excel'),
        ('Personal Finance Dashboard', 'personal-finance-dashboard', 'personal finance dashboard excel'),
        ('Stock Trading Journal Template', 'stock-trading-journal-template', 'stock trading journal excel'),
        ('Crypto Portfolio Tracker', 'crypto-portfolio-tracker', 'crypto portfolio tracker excel'),
        ('Income Tax Estimator Worksheet', 'income-tax-estimator-worksheet', 'income tax estimator excel'),
        ('Debt Snowball Payoff Plan', 'debt-snowball-payoff-plan', 'debt snowball payoff excel'),
        ('Emergency Fund Planner', 'emergency-fund-planner', 'emergency fund planner excel'),
        ('Mutual Fund SIP Tracker', 'mutual-fund-sip-tracker', 'mutual fund sip tracker excel'),
        ('FIRE Movement Calculator', 'fire-movement-calculator', 'fire movement calculator excel'),
        ('Real Estate ROI Tracker', 'real-estate-roi-tracker', 'real estate roi tracker excel'),
        ('Business Cash Reserve Plan', 'business-cash-reserve-plan', 'business cash reserve plan excel'),
        ('Working Capital Tracker', 'working-capital-tracker', 'working capital tracker excel'),
        ('Break Even Analysis Tool', 'break-even-analysis-tool', 'break even analysis excel'),
        ('Financial Forecast Model', 'financial-forecast-model', 'financial forecast model excel'),
        ('NPV IRR Calculator Template', 'npv-irr-calculator-template', 'npv irr calculator excel'),
        ('Capital Budgeting Tool', 'capital-budgeting-tool', 'capital budgeting tool excel'),
        ('Loan Comparison Sheet', 'loan-comparison-sheet', 'loan comparison sheet excel'),
        ('Insurance Coverage Planner', 'insurance-coverage-planner', 'insurance coverage planner excel'),
        ('Will and Estate Worksheet', 'will-and-estate-worksheet', 'will and estate worksheet excel'),
        ('Sinking Fund Tracker', 'sinking-fund-tracker', 'sinking fund tracker excel'),
        ('Goal Based Savings Tracker', 'goal-based-savings-tracker', 'goal based savings tracker excel'),
        ('Quarterly Financial Review Sheet', 'quarterly-financial-review-sheet', 'quarterly financial review excel'),
    ],
    'Inventory': [
        ('Warehouse Inventory Tracker', 'warehouse-inventory-tracker', 'warehouse inventory tracker excel'),
        ('Restaurant Food Inventory', 'restaurant-food-inventory', 'restaurant food inventory excel'),
        ('Retail Store Stock Sheet', 'retail-store-stock-sheet', 'retail store stock sheet excel'),
        ('Office Supplies Inventory', 'office-supplies-inventory', 'office supplies inventory excel'),
        ('Equipment Asset Register', 'equipment-asset-register', 'equipment asset register excel'),
        ('Tool Inventory Log Template', 'tool-inventory-log-template', 'tool inventory log excel'),
        ('Library Book Inventory Sheet', 'library-book-inventory-sheet', 'library book inventory excel'),
        ('IT Hardware Asset Tracker', 'it-hardware-asset-tracker', 'it hardware asset tracker excel'),
        ('Pharmacy Drug Inventory', 'pharmacy-drug-inventory', 'pharmacy drug inventory excel'),
        ('Vehicle Fleet Inventory Sheet', 'vehicle-fleet-inventory-sheet', 'vehicle fleet inventory excel'),
        ('Manufacturing Raw Materials Sheet', 'manufacturing-raw-materials-sheet', 'manufacturing raw materials excel'),
        ('Construction Material Tracker', 'construction-material-tracker', 'construction material tracker excel'),
        ('Home Asset Inventory List', 'home-asset-inventory-list', 'home asset inventory excel'),
        ('Rental Property Asset List', 'rental-property-asset-list', 'rental property asset excel'),
        ('Salon Stock Inventory Sheet', 'salon-stock-inventory-sheet', 'salon stock inventory excel'),
    ],
    'Invoice': [
        ('Professional Service Invoice Template', 'professional-service-invoice-template', 'professional service invoice excel'),
        ('GST Tax Invoice India Template', 'gst-tax-invoice-india-template', 'gst tax invoice india excel'),
        ('Freelancer Hourly Invoice', 'freelancer-hourly-invoice', 'freelancer hourly invoice excel'),
        ('Pro Forma Invoice Template', 'pro-forma-invoice-template', 'pro forma invoice excel'),
        ('Commercial Export Invoice', 'commercial-export-invoice', 'commercial export invoice excel'),
        ('Recurring Subscription Invoice', 'recurring-subscription-invoice', 'recurring subscription invoice excel'),
        ('Construction Contractor Invoice', 'construction-contractor-invoice', 'construction contractor invoice excel'),
        ('Medical Practice Invoice', 'medical-practice-invoice', 'medical practice invoice excel'),
        ('Restaurant Bill Invoice Template', 'restaurant-bill-invoice-template', 'restaurant bill invoice excel'),
        ('Retail Sales Invoice Template', 'retail-sales-invoice-template', 'retail sales invoice excel'),
        ('Consultancy Project Invoice', 'consultancy-project-invoice', 'consultancy project invoice excel'),
        ('Photography Service Invoice', 'photography-service-invoice', 'photography service invoice excel'),
        ('Web Design Invoice Template', 'web-design-invoice-template', 'web design invoice excel'),
        ('Event Planner Invoice Template', 'event-planner-invoice-template', 'event planner invoice excel'),
        ('Legal Services Invoice Template', 'legal-services-invoice-template', 'legal services invoice excel'),
        ('Auto Repair Workshop Invoice', 'auto-repair-workshop-invoice', 'auto repair workshop invoice excel'),
        ('Catering Service Invoice', 'catering-service-invoice', 'catering service invoice excel'),
        ('Cleaning Service Invoice', 'cleaning-service-invoice', 'cleaning service invoice excel'),
        ('Tutoring Hourly Invoice', 'tutoring-hourly-invoice', 'tutoring hourly invoice excel'),
        ('Wholesale Bulk Invoice Template', 'wholesale-bulk-invoice-template', 'wholesale bulk invoice excel'),
    ],
    'Planner-Tracker': [
        ('Daily Productivity Planner', 'daily-productivity-planner', 'daily productivity planner excel'),
        ('Weekly Goal Tracker Template', 'weekly-goal-tracker-template', 'weekly goal tracker excel'),
        ('Monthly Habit Tracker Template', 'monthly-habit-tracker-template', 'monthly habit tracker excel'),
        ('Yearly Vision Planner Template', 'yearly-vision-planner-template', 'yearly vision planner excel'),
        ('Project Milestone Tracker', 'project-milestone-tracker', 'project milestone tracker excel'),
        ('Workout Fitness Tracker', 'workout-fitness-tracker', 'workout fitness tracker excel'),
        ('Weekly Meal Plan Tracker', 'weekly-meal-plan-tracker', 'weekly meal plan tracker excel'),
        ('Reading Book Tracker Template', 'reading-book-tracker-template', 'reading book tracker excel'),
        ('Sleep Quality Tracker', 'sleep-quality-tracker', 'sleep quality tracker excel'),
        ('Mood Wellness Journal', 'mood-wellness-journal', 'mood wellness journal excel'),
        ('Water Intake Tracker', 'water-intake-tracker', 'water intake tracker excel'),
        ('Daily Expense Tracker Sheet', 'daily-expense-tracker-sheet', 'daily expense tracker excel'),
        ('Time Block Day Planner', 'time-block-day-planner', 'time block day planner excel'),
        ('OKR Quarterly Tracker', 'okr-quarterly-tracker', 'okr quarterly tracker excel'),
        ('KPI Performance Tracker', 'kpi-performance-tracker', 'kpi performance tracker excel'),
        ('Job Application Tracker', 'job-application-tracker', 'job application tracker excel'),
        ('Travel Trip Planner Template', 'travel-trip-planner-template', 'travel trip planner excel'),
        ('Wedding Planning Checklist', 'wedding-planning-checklist', 'wedding planning checklist excel'),
        ('Study Goal Tracker Template', 'study-goal-tracker-template', 'study goal tracker excel'),
    ],
    'Schedule': [
        ('Weekly Class Schedule Template', 'weekly-class-schedule-template', 'weekly class schedule excel'),
        ('Employee Shift Schedule', 'employee-shift-schedule', 'employee shift schedule excel'),
        ('Project Gantt Schedule', 'project-gantt-schedule', 'project gantt schedule excel'),
        ('Production Line Schedule', 'production-line-schedule', 'production line schedule excel'),
        ('Hospital Duty Roster Schedule', 'hospital-duty-roster-schedule', 'hospital duty roster excel'),
        ('Restaurant Staff Schedule', 'restaurant-staff-schedule', 'restaurant staff schedule excel'),
        ('School Bell Schedule Template', 'school-bell-schedule-template', 'school bell schedule excel'),
        ('University Exam Schedule', 'university-exam-schedule', 'university exam schedule excel'),
        ('Cleaning Maintenance Schedule', 'cleaning-maintenance-schedule', 'cleaning maintenance schedule excel'),
        ('Construction Project Schedule', 'construction-project-schedule', 'construction project schedule excel'),
        ('Event Run of Show Schedule', 'event-run-of-show-schedule', 'event run of show schedule excel'),
        ('Wedding Day Schedule Template', 'wedding-day-schedule-template', 'wedding day schedule excel'),
        ('Vacation Itinerary Schedule', 'vacation-itinerary-schedule', 'vacation itinerary schedule excel'),
        ('Sports Tournament Schedule', 'sports-tournament-schedule', 'sports tournament schedule excel'),
        ('Conference Session Schedule', 'conference-session-schedule', 'conference session schedule excel'),
        ('Marketing Campaign Schedule', 'marketing-campaign-schedule', 'marketing campaign schedule excel'),
        ('Social Content Posting Schedule', 'social-content-posting-schedule', 'social content posting schedule excel'),
        ('Software Sprint Schedule', 'software-sprint-schedule', 'software sprint schedule excel'),
        ('Hiring Interview Schedule', 'hiring-interview-schedule', 'hiring interview schedule excel'),
        ('On Call Rotation Schedule', 'on-call-rotation-schedule', 'on call rotation schedule excel'),
        ('Delivery Route Schedule', 'delivery-route-schedule', 'delivery route schedule excel'),
        ('Bus Driver Schedule Template', 'bus-driver-schedule-template', 'bus driver schedule excel'),
        ('Pilot Crew Roster Schedule', 'pilot-crew-roster-schedule', 'pilot crew roster excel'),
        ('Family Daily Schedule Template', 'family-daily-schedule-template', 'family daily schedule excel'),
        ('Daycare Activity Schedule', 'daycare-activity-schedule', 'daycare activity schedule excel'),
        ('Therapy Session Schedule', 'therapy-session-schedule', 'therapy session schedule excel'),
        ('Garden Watering Schedule', 'garden-watering-schedule', 'garden watering schedule excel'),
        ('Pet Care Daily Schedule', 'pet-care-daily-schedule', 'pet care daily schedule excel'),
        ('Vehicle Maintenance Schedule', 'vehicle-maintenance-schedule', 'vehicle maintenance schedule excel'),
        ('Fitness Training Schedule', 'fitness-training-schedule', 'fitness training schedule excel'),
    ],
    'Student': [
        ('Class Attendance Register', 'class-attendance-register', 'class attendance register excel'),
        ('Assignment Submission Tracker', 'assignment-submission-tracker', 'assignment submission tracker excel'),
        ('Semester Grade Calculator', 'semester-grade-calculator', 'semester grade calculator excel'),
        ('Scholarship Application Tracker', 'scholarship-application-tracker', 'scholarship application tracker excel'),
        ('Study Hours Logger Template', 'study-hours-logger-template', 'study hours logger excel'),
    ],
    'Timeline': [
        ('Project Roadmap Timeline', 'project-roadmap-timeline', 'project roadmap timeline excel'),
        ('Product Launch Timeline', 'product-launch-timeline', 'product launch timeline excel'),
        ('Marketing Campaign Timeline', 'marketing-campaign-timeline', 'marketing campaign timeline excel'),
        ('Construction Phase Timeline', 'construction-phase-timeline', 'construction phase timeline excel'),
        ('Software Release Timeline', 'software-release-timeline', 'software release timeline excel'),
        ('Event Planning Timeline', 'event-planning-timeline', 'event planning timeline excel'),
        ('Wedding Preparation Timeline', 'wedding-preparation-timeline', 'wedding preparation timeline excel'),
        ('Career Milestone Timeline', 'career-milestone-timeline', 'career milestone timeline excel'),
        ('Company History Timeline', 'company-history-timeline', 'company history timeline excel'),
        ('Research Project Timeline', 'research-project-timeline', 'research project timeline excel'),
        ('Academic Semester Timeline', 'academic-semester-timeline', 'academic semester timeline excel'),
        ('Hiring Recruitment Timeline', 'hiring-recruitment-timeline', 'hiring recruitment timeline excel'),
    ],
    'Timesheet': [
        ('Weekly Employee Timesheet', 'weekly-employee-timesheet', 'weekly employee timesheet excel'),
        ('Bi Weekly Hourly Timesheet', 'bi-weekly-hourly-timesheet', 'bi weekly hourly timesheet excel'),
        ('Monthly Salary Timesheet', 'monthly-salary-timesheet', 'monthly salary timesheet excel'),
        ('Project Time Tracking Sheet', 'project-time-tracking-sheet', 'project time tracking excel'),
        ('Freelancer Hourly Log Sheet', 'freelancer-hourly-log-sheet', 'freelancer hourly log excel'),
        ('Consultant Billing Timesheet', 'consultant-billing-timesheet', 'consultant billing timesheet excel'),
        ('Construction Worker Timesheet', 'construction-worker-timesheet', 'construction worker timesheet excel'),
        ('IT Engineer Timesheet', 'it-engineer-timesheet', 'it engineer timesheet excel'),
        ('Lawyer Billable Hours Sheet', 'lawyer-billable-hours-sheet', 'lawyer billable hours excel'),
        ('Doctor On Call Hours Log', 'doctor-on-call-hours-log', 'doctor on call hours excel'),
        ('Tutor Teaching Hours Log', 'tutor-teaching-hours-log', 'tutor teaching hours excel'),
        ('Cleaning Staff Hours Log', 'cleaning-staff-hours-log', 'cleaning staff hours excel'),
        ('Driver Logbook Hours Sheet', 'driver-logbook-hours-sheet', 'driver logbook hours excel'),
        ('Multi Project Allocation Timesheet', 'multi-project-allocation-timesheet', 'multi project allocation timesheet excel'),
    ],
}

# Validate counts
COUNTS = {'Accounting':9,'Budget':26,'Calculator':2,'Calendars':2,'Chart':27,'Financial-Management':25,
          'Inventory':15,'Invoice':20,'Planner-Tracker':19,'Schedule':30,'Student':5,'Timeline':12,'Timesheet':14}

for c, exp in COUNTS.items():
    actual = len(NAME_POOLS[c])
    assert actual == exp, f'{c}: have {actual}, need {exp}'
print('All name pools complete:', sum(COUNTS.values()), 'unique names')

CAT_META = {
    'Accounting':           {'slug':'excel-accounting',           'audience':'small business owners and freelance accountants', 'use':'manage day-to-day bookkeeping in Excel'},
    'Budget':               {'slug':'excel-budget',               'audience':'individuals, families and finance teams', 'use':'plan, track and control spending across categories'},
    'Calculator':           {'slug':'excel-calculator',           'audience':'borrowers, planners and analysts', 'use':'run financial calculations with editable inputs'},
    'Calendars':            {'slug':'excel-calendars',            'audience':'students, marketers and managers', 'use':'plan dates, deadlines and content workflows'},
    'Chart':                {'slug':'excel-chart',                'audience':'analysts, managers and presenters', 'use':'visualise data and tell a clear story'},
    'Financial-Management': {'slug':'excel-financial-management', 'audience':'investors, founders and finance professionals', 'use':'monitor money, plan growth and protect downside'},
    'Inventory':            {'slug':'excel-inventory',            'audience':'shopkeepers, store managers and operations teams', 'use':'track stock levels, reorder points and asset value'},
    'Invoice':              {'slug':'excel-invoice',              'audience':'freelancers, agencies and small businesses', 'use':'bill clients quickly with a clean, GST-ready format'},
    'Planner-Tracker':      {'slug':'excel-planner-tracker',      'audience':'professionals, students and goal setters', 'use':'plan tasks, track habits and stay on schedule'},
    'Schedule':             {'slug':'excel-schedule',             'audience':'managers, teachers and project leads', 'use':'organise people, shifts and milestones in one place'},
    'Student':              {'slug':'excel-student',              'audience':'school and college students', 'use':'manage academics, attendance and grades easily'},
    'Timeline':             {'slug':'excel-timeline',             'audience':'project managers, marketers and planners', 'use':'communicate phases, milestones and dates clearly'},
    'Timesheet':            {'slug':'excel-timesheet',            'audience':'hourly workers, contractors and HR teams', 'use':'log working hours and calculate payroll accurately'},
}
